services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:5000 main:app

  trafico:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:5001 main:app
    deploy:
      replicas: 3

  tiempo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APIKEY
    command: gunicorn -w 4 -b 0.0.0.0:5002 main:app
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - test
      - trafico
      - tiempo
