apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-service 
spec: 
  type: NodePort 
  selector: 
    app: nginx 
  ports: 
    - protocol: TCP 
      port: 80 
      nodePort: 30030 


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: api 
        image: josubarru/ipmd:practica1
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: mysecret

